In [3]:
from openpyxl import load_workbook
import pandas as pd

wb = load_workbook(filename='data/Stefan surgical 2019.xlsx', read_only=True)

In [49]:
def load_demographics(wb):
  ws = wb['Demographics']
  data = ws.values
  next(data)
  cols = next(data)
  cols = [x.lower() for x in cols]
  data = list(data)
  df = pd.DataFrame(data, columns=cols)
  df = df.drop(['first name', 'second name'], axis=1)
  df = df.replace(r'\s*(.*?)\s*', r'\1', regex=True)
  df = df.set_index(['record number'])
  binary_cols = df.columns[5:]
  df[binary_cols] = df[binary_cols].replace(['Yes', 'No'], [1, 0])
  df[['covid status']] = df[['covid status']].replace(['Negative', 'Positive', 'N/A'], [0,1, None])
  return df

In [11]:
def load_imaging(wb):
  ws = wb['Imaging']
  data = ws.values
  next(data)
  cols = next(data)
  cols = [x.lower() for x in cols]
  data = list(data)
  df = pd.DataFrame(data, columns=cols)
  binary_cols = df.columns[:-1]
  df[binary_cols] = df[binary_cols].replace(r'\s*(.*?)\s*', r'\1', regex=True)
  df[binary_cols] = df[binary_cols].replace(['Yes', 'No', 'NA'], [1, 0, None])
  df = df.set_index(['record number'])
  return df

In [13]:
def load_management(wb):
  ws = wb['Management']
  data = ws.values
  next(data)
  cols = next(data)
  cols = [x.lower() for x in cols]
  cols[-1] = 'reoperated'
  data = list(data)
  df = pd.DataFrame(data, columns=cols)
  binary_cols = df.columns[1:]
  df[binary_cols] = df[binary_cols].replace(r'\s*(.*?)\s*', r'\1', regex=True)
  df[binary_cols] = df[binary_cols].replace(['Yes', 'No'], [1, 0])
  df = df.set_index(['record number'])
  return df

In [ ]:
def load_operations(wb):
  ws = wb['Operative data']
  data = ws.values
  next(data)
  cols = next(data)
  cols = [x.lower() for x in cols]
  cols[-1] = 'reoperated'
  data = list(data)
  df = pd.DataFrame(data, columns=cols)
  binary_cols = df.columns[1:]
  df[binary_cols] = df[binary_cols].replace(r'\s*(.*?)\s*', r'\1', regex=True)
  df[binary_cols] = df[binary_cols].replace(['Yes', 'No'], [1, 0])
  df = df.set_index(['record number'])
  return df

In [14]:
df = load_management(wb)
df.head()

               ir  conservative  surgical  reoperated
record number
DIS0358375      0             0         1           0
DIS0536947      0             0         1           0
DIS0649924      0             0         1           0
DIS0732094      0             0         1           0
DIS0959536      0             0         1           0

In [10]:
df[df.columns[:-1]]

               imaging  us scan  ct scan  faecolith  free fluid
record number
DIS0358375           1        0        1        0.0         0.0
DIS0536947           1        0        1        1.0         NaN
DIS0649924           0        0        0        NaN         NaN
DIS0732094           0        0        0        NaN         NaN
DIS0959536           0        0        0        NaN         NaN
...                ...      ...      ...        ...         ...
DIS1083599           1        0        1        0.0         1.0
DIS1085993           0        0        0        NaN         NaN
DIS1256243           0        0        0        NaN         NaN
DIS1259184           0        0        0        NaN         NaN
DIS1252320           1        0        1        0.0         0.0

[70 rows x 5 columns]

In [50]:
df = load_demographics(wb)
df.head()

,age,gender,bmi,smoker,none,htn,diabetes,ihd,airway,vascular,immunocompromised,covid status
record number,,,,,,,,,,,,
DIS0358375,86,Male,32.1,Never,None,1,1,1,0,0,0,0.0
DIS0536947,43,Female,NaN,Never,None,0,0,0,0,0,0,NaN
DIS0649924,22,Male,20.1,Current,None,0,0,0,0,0,0,NaN
DIS0732094,18,Male,22.8,Never,None,0,0,0,0,0,0,NaN
DIS0959536,10,Female,NaN,Never,None,0,0,0,0,0,0,NaN